# Generated by Django 5.1.3 on 2024-12-04 12:51

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="banner_background_image1",
            field=models.ForeignKey(
                blank=True,
                help_text="The first banner background image.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="banner_background_image2",
            field=models.ForeignKey(
                blank=True,
                help_text="The second banner background image.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="banner_background_image3",
            field=models.ForeignKey(
                blank=True,
                help_text="The third banner background image.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="button",
            field=models.ForeignKey(
                blank=True,
                help_text="Select an optional page to link to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="button_text",
            field=models.CharField(
                default="Read More", help_text="Button text", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="content",
            field=models.TextField(
                blank=True, help_text="Content text below the carousel."
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="header_background_image",
            field=models.ForeignKey(
                blank=True,
                help_text="The banner background image.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="lead_text",
            field=models.CharField(
                blank=True,
                help_text="Subheading text under the banner title",
                max_length=140,
            ),
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Title of the album.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Description of the album."
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Price of the album.", max_digits=10
                    ),
                ),
                (
                    "venmo_id",
                    models.CharField(
                        blank=True, help_text="Venmo ID for payment.", max_length=255
                    ),
                ),
                (
                    "buy_url",
                    models.URLField(blank=True, help_text="URL to purchase the album."),
                ),
                (
                    "homepage",
                    modelcluster.fields.ParentalKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albums",
                        to="home.homepage",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Album cover image.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the show.", max_length=255),
                ),
                (
                    "date_time",
                    models.DateTimeField(help_text="Date and time of the show."),
                ),
                (
                    "venue",
                    models.CharField(help_text="Venue of the show.", max_length=255),
                ),
                (
                    "venue_url",
                    models.URLField(
                        blank=True, help_text="Google Maps link or URL for the venue."
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Description of the show."
                    ),
                ),
                (
                    "ticket_url",
                    models.URLField(
                        blank=True, help_text="URL for purchasing tickets."
                    ),
                ),
                (
                    "homepage",
                    modelcluster.fields.ParentalKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shows",
                        to="home.homepage",
                    ),
                ),
                (
                    "poster_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Poster image for the show.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Single",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Title of the single",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Description of the single."
                    ),
                ),
                (
                    "buy_url",
                    models.URLField(
                        blank=True, help_text="URL to purchase the single."
                    ),
                ),
                (
                    "homepage",
                    modelcluster.fields.ParentalKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="singles",
                        to="home.homepage",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image for the single.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
